import {
  Briefcase,
  Building2,
  Car,
  Clapperboard,
  CreditCard,
  Gift,
  GraduationCap,
  Handshake,
  HeartPulse,
  Home,
  Lightbulb,
  LucideIcon,
  PawPrint,
  PiggyBank,
  Plane,
  Shirt,
  ShoppingCart,
  SoapDispenserDroplet,
  Tag,
  Utensils,
  Wrench,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  Home,
  Utensils,
  Car,
  HeartPulse,
  GraduationCap,
  Briefcase,
  Clapperboard,
  Plane,
  Shirt,
  PawPrint,
  Lightbulb,
  PiggyBank,
  Gift,
  SoapDispenserDroplet,
  Tag,
  CreditCard,
  ShoppingCart,
  Wrench,
  Building2,
  Handshake,
};

export type IconName = keyof typeof ICON_MAP;
export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];
